"""initial

Revision ID: 22f40f683295
Revises: 
Create Date: 2026-05-26 09:52:31.579759

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '22f40f683295'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('franchise_code_counter',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('last_sequence', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('year')
    )
    op.create_table('franchises',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('franchise_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('current_address', sa.String(length=500), nullable=True),
    sa.Column('permanent_address', sa.String(length=500), nullable=True),
    sa.Column('proposed_location', sa.String(length=255), nullable=True),
    sa.Column('ownership_type', sa.String(length=20), nullable=True),
    sa.Column('detailed_business_address', sa.String(length=500), nullable=True),
    sa.Column('prior_experience', sa.String(length=500), nullable=True),
    sa.Column('years_active', sa.Integer(), nullable=True),
    sa.Column('office_space_sqft', sa.Integer(), nullable=True),
    sa.Column('office_ownership', sa.String(length=20), nullable=True),
    sa.Column('staff_count', sa.Integer(), nullable=True),
    sa.Column('internet_availability', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('computer_laptop', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('investment_capacity', sa.String(length=100), nullable=True),
    sa.Column('source_of_funds', sa.String(length=255), nullable=True),
    sa.Column('bank_name', sa.String(length=255), nullable=True),
    sa.Column('account_number', sa.String(length=50), nullable=True),
    sa.Column('existing_loans', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('existing_loan_details', sa.String(length=1000), nullable=True),
    sa.Column('preferred_service_area', sa.String(length=255), nullable=True),
    sa.Column('nearby_landmark', sa.String(length=255), nullable=True),
    sa.Column('pincode', sa.String(length=6), nullable=False),
    sa.Column('doc_id_proof', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('doc_address_proof', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('doc_photographs', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('doc_business_registration', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('doc_bank_statement', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('agree_to_terms', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('submission_place', sa.String(length=255), nullable=True),
    sa.Column('submission_date', sa.Date(), nullable=True),
    sa.Column('employee_counter', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_franchises_franchise_code'), 'franchises', ['franchise_code'], unique=True)
    op.create_table('fuel_config',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('effective_from', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gst_config',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=150), nullable=False),
    sa.Column('module', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_action'), 'permissions', ['action'], unique=False)
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=True)
    op.create_index(op.f('ix_permissions_module'), 'permissions', ['module'], unique=False)
    op.create_table('pincode_serviceability',
    sa.Column('pincode', sa.String(length=20), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('serviceable', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.PrimaryKeyConstraint('pincode')
    )
    op.create_table('pricing_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('calculator_type', sa.String(length=20), nullable=False),
    sa.Column('shipment_type', sa.String(length=20), nullable=False),
    sa.Column('payment_mode', sa.String(length=20), nullable=False),
    sa.Column('risk_type', sa.String(length=30), nullable=False),
    sa.Column('min_weight', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_weight', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('base_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_per_kg', sa.Numeric(precision=10, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('cod_charge', sa.Numeric(precision=10, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('reverse_charge', sa.Numeric(precision=10, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('fuel_surcharge_percent', sa.Numeric(precision=5, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('insurance_percent', sa.Numeric(precision=5, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('gst_percent', sa.Numeric(precision=5, scale=2), server_default=sa.text('18'), nullable=False),
    sa.Column('volumetric_divisor', sa.Numeric(precision=10, scale=2), server_default=sa.text('5000'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pricing_rules_calculator_type'), 'pricing_rules', ['calculator_type'], unique=False)
    op.create_index(op.f('ix_pricing_rules_payment_mode'), 'pricing_rules', ['payment_mode'], unique=False)
    op.create_index(op.f('ix_pricing_rules_risk_type'), 'pricing_rules', ['risk_type'], unique=False)
    op.create_index(op.f('ix_pricing_rules_shipment_type'), 'pricing_rules', ['shipment_type'], unique=False)
    op.create_table('pricing_zones',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('zone_name', sa.String(length=100), nullable=False),
    sa.Column('pickup_region', sa.String(length=100), nullable=False),
    sa.Column('delivery_region', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pricing_zones_delivery_region'), 'pricing_zones', ['delivery_region'], unique=False)
    op.create_index(op.f('ix_pricing_zones_pickup_region'), 'pricing_zones', ['pickup_region'], unique=False)
    op.create_index(op.f('ix_pricing_zones_zone_name'), 'pricing_zones', ['zone_name'], unique=True)
    op.create_table('rate_cards',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('customer_type', sa.String(length=20), nullable=False),
    sa.Column('shipment_type', sa.String(length=20), nullable=False),
    sa.Column('zone', sa.String(length=50), nullable=False),
    sa.Column('min_weight', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_weight', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('base_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('additional_kg_price', sa.Numeric(precision=10, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('cod_charge', sa.Numeric(precision=10, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('insurance_charge', sa.Numeric(precision=10, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('appointment_charge', sa.Numeric(precision=10, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rate_cards_customer_type'), 'rate_cards', ['customer_type'], unique=False)
    op.create_index(op.f('ix_rate_cards_shipment_type'), 'rate_cards', ['shipment_type'], unique=False)
    op.create_index(op.f('ix_rate_cards_zone'), 'rate_cards', ['zone'], unique=False)
    op.create_table('rate_zones',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('zone_name', sa.String(length=50), nullable=False),
    sa.Column('state_mapping', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rate_zones_zone_name'), 'rate_zones', ['zone_name'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('pincode', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('profile_image', sa.String(length=500), nullable=True),
    sa.Column('franchise_id', sa.String(length=36), nullable=True),
    sa.Column('employee_code', sa.String(length=80), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['franchise_id'], ['franchises.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_employee_code'), 'users', ['employee_code'], unique=True)
    op.create_index(op.f('ix_users_franchise_id'), 'users', ['franchise_id'], unique=False)
    op.create_table('activity_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_logs_user_id'), 'activity_logs', ['user_id'], unique=False)
    op.create_table('bags',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('bag_number', sa.String(length=50), nullable=False),
    sa.Column('barcode', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), server_default=sa.text("'Processing'"), nullable=False),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('total_orders', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bags_bag_number'), 'bags', ['bag_number'], unique=True)
    op.create_index(op.f('ix_bags_created_by'), 'bags', ['created_by'], unique=False)
    op.create_index(op.f('ix_bags_pincode'), 'bags', ['pincode'], unique=False)
    op.create_table('cash_vouchers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('voucher_no', sa.String(length=50), nullable=False),
    sa.Column('franchise_id', sa.String(length=36), nullable=True),
    sa.Column('voucher_date', sa.Date(), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_mode', sa.String(length=30), server_default=sa.text("'Cash'"), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['franchise_id'], ['franchises.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cash_vouchers_created_by'), 'cash_vouchers', ['created_by'], unique=False)
    op.create_index(op.f('ix_cash_vouchers_franchise_id'), 'cash_vouchers', ['franchise_id'], unique=False)
    op.create_index(op.f('ix_cash_vouchers_voucher_no'), 'cash_vouchers', ['voucher_no'], unique=True)
    op.create_table('consignees',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('franchise_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('mobile', sa.String(length=20), nullable=False),
    sa.Column('alternate_mobile', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address_line_1', sa.String(length=500), nullable=False),
    sa.Column('address_line_2', sa.String(length=500), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=10), server_default=sa.text("'active'"), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['franchise_id'], ['franchises.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consignees_franchise_id'), 'consignees', ['franchise_id'], unique=False)
    op.create_index(op.f('ix_consignees_pincode'), 'consignees', ['pincode'], unique=False)
    op.create_index(op.f('ix_consignees_user_id'), 'consignees', ['user_id'], unique=False)
    op.create_table('expenses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('franchise_id', sa.String(length=36), nullable=True),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('expense_head', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('approved_by', sa.String(length=36), nullable=True),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['franchise_id'], ['franchises.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_created_by'), 'expenses', ['created_by'], unique=False)
    op.create_index(op.f('ix_expenses_franchise_id'), 'expenses', ['franchise_id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('franchise_id', sa.String(length=36), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), server_default=sa.text('18'), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('orders_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'issued'"), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['franchise_id'], ['franchises.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_franchise_id'), 'invoices', ['franchise_id'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=True)
    op.create_table('manifests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('manifest_no', sa.String(length=50), nullable=False),
    sa.Column('franchise_id', sa.String(length=36), nullable=True),
    sa.Column('manifest_date', sa.Date(), nullable=False),
    sa.Column('vehicle_no', sa.String(length=50), nullable=True),
    sa.Column('route', sa.String(length=150), nullable=True),
    sa.Column('status', sa.String(length=30), server_default=sa.text("'created'"), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['franchise_id'], ['franchises.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manifests_created_by'), 'manifests', ['created_by'], unique=False)
    op.create_index(op.f('ix_manifests_franchise_id'), 'manifests', ['franchise_id'], unique=False)
    op.create_index(op.f('ix_manifests_manifest_date'), 'manifests', ['manifest_date'], unique=False)
    op.create_index(op.f('ix_manifests_manifest_no'), 'manifests', ['manifest_no'], unique=True)
    op.create_table('pickup_addresses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('franchise_id', sa.String(length=36), nullable=True),
    sa.Column('nickname', sa.String(length=100), nullable=False),
    sa.Column('contact_name', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address_line_1', sa.String(length=500), nullable=False),
    sa.Column('address_line_2', sa.String(length=500), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), server_default=sa.text("'India'"), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['franchise_id'], ['franchises.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pickup_addresses_franchise_id'), 'pickup_addresses', ['franchise_id'], unique=False)
    op.create_index(op.f('ix_pickup_addresses_pincode'), 'pickup_addresses', ['pincode'], unique=False)
    op.create_index(op.f('ix_pickup_addresses_user_id'), 'pickup_addresses', ['user_id'], unique=False)
    op.create_table('remittances',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('franchise_id', sa.String(length=36), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('orders_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('remitted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['franchise_id'], ['franchises.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_remittances_franchise_id'), 'remittances', ['franchise_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('review', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_permissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('permission_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permission')
    )
    op.create_table('staff_attendance',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('franchise_id', sa.String(length=36), nullable=True),
    sa.Column('attendance_date', sa.Date(), nullable=False),
    sa.Column('check_in', sa.DateTime(), nullable=True),
    sa.Column('check_out', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'present'"), nullable=False),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['franchise_id'], ['franchises.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_attendance_attendance_date'), 'staff_attendance', ['attendance_date'], unique=False)
    op.create_index(op.f('ix_staff_attendance_franchise_id'), 'staff_attendance', ['franchise_id'], unique=False)
    op.create_index(op.f('ix_staff_attendance_user_id'), 'staff_attendance', ['user_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('assigned_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_user_single_role')
    )
    op.create_table('wallets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('franchise_id', sa.String(length=36), nullable=False),
    sa.Column('balance', sa.Numeric(precision=14, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['franchise_id'], ['franchises.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallets_franchise_id'), 'wallets', ['franchise_id'], unique=True)
    op.create_table('warehouse_addresses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('franchise_id', sa.String(length=36), nullable=True),
    sa.Column('nickname', sa.String(length=100), nullable=False),
    sa.Column('contact_name', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address_line_1', sa.String(length=500), nullable=False),
    sa.Column('address_line_2', sa.String(length=500), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), server_default=sa.text("'India'"), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['franchise_id'], ['franchises.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouse_addresses_franchise_id'), 'warehouse_addresses', ['franchise_id'], unique=False)
    op.create_index(op.f('ix_warehouse_addresses_pincode'), 'warehouse_addresses', ['pincode'], unique=False)
    op.create_index(op.f('ix_warehouse_addresses_user_id'), 'warehouse_addresses', ['user_id'], unique=False)
    op.create_table('bulk_orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('order_type', sa.String(length=20), nullable=False),
    sa.Column('pickup_address_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('total_orders', sa.Integer(), nullable=False),
    sa.Column('successful_orders', sa.Integer(), nullable=False),
    sa.Column('failed_orders', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('franchise_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['franchise_id'], ['franchises.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pickup_address_id'], ['pickup_addresses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bulk_orders_created_by'), 'bulk_orders', ['created_by'], unique=False)
    op.create_index(op.f('ix_bulk_orders_franchise_id'), 'bulk_orders', ['franchise_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('bulk_order_id', sa.String(length=36), nullable=True),
    sa.Column('order_number', sa.String(length=50), nullable=False),
    sa.Column('order_type', sa.String(length=20), nullable=False),
    sa.Column('pickup_address_id', sa.String(length=36), nullable=False),
    sa.Column('consignee_id', sa.String(length=36), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=False),
    sa.Column('cod_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('to_pay_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('rov', sa.String(length=20), nullable=False),
    sa.Column('order_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_weight_kg', sa.Numeric(precision=10, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('total_vol_weight_kg', sa.Numeric(precision=10, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('applicable_weight_kg', sa.Numeric(precision=10, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('total_boxes', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('shipping_charge', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('gst_number', sa.String(length=20), nullable=True),
    sa.Column('eway_bill_number', sa.String(length=30), nullable=True),
    sa.Column('barcode', sa.Text(), nullable=True),
    sa.Column('previous_status', sa.String(length=150), nullable=True),
    sa.Column('status', sa.String(length=150), server_default=sa.text("'Processing'"), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('franchise_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bulk_order_id'], ['bulk_orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['consignee_id'], ['consignees.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['franchise_id'], ['franchises.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pickup_address_id'], ['pickup_addresses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_bulk_order_id'), 'orders', ['bulk_order_id'], unique=False)
    op.create_index(op.f('ix_orders_created_by'), 'orders', ['created_by'], unique=False)
    op.create_index(op.f('ix_orders_franchise_id'), 'orders', ['franchise_id'], unique=False)
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=True)
    op.create_table('bag_orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('bag_id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('scanned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bag_id'], ['bags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bag_orders_bag_id'), 'bag_orders', ['bag_id'], unique=False)
    op.create_index(op.f('ix_bag_orders_order_id'), 'bag_orders', ['order_id'], unique=False)
    op.create_table('consigneestodelivery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pincode', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('order_id', sa.String(length=36), nullable=True),
    sa.Column('consignee_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['consignee_id'], ['consignees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consigneestodelivery_id'), 'consigneestodelivery', ['id'], unique=False)
    op.create_index(op.f('ix_consigneestodelivery_user_id'), 'consigneestodelivery', ['user_id'], unique=False)
    op.create_table('franchisetodelivery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pincode', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('order_id', sa.String(length=36), nullable=True),
    sa.Column('franchise_addresses_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['franchise_addresses_id'], ['franchises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_franchisetodelivery_id'), 'franchisetodelivery', ['id'], unique=False)
    op.create_index(op.f('ix_franchisetodelivery_user_id'), 'franchisetodelivery', ['user_id'], unique=False)
    op.create_table('invoice_orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('invoice_id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('shipping_charge', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_orders_invoice_id'), 'invoice_orders', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_invoice_orders_order_id'), 'invoice_orders', ['order_id'], unique=True)
    op.create_table('manifest_orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('manifest_id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['manifest_id'], ['manifests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manifest_orders_manifest_id'), 'manifest_orders', ['manifest_id'], unique=False)
    op.create_index(op.f('ix_manifest_orders_order_id'), 'manifest_orders', ['order_id'], unique=True)
    op.create_table('order_franchise_addresses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('franchise_address_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['franchise_address_id'], ['franchises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_table('order_packages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('count', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('length_cm', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('breadth_cm', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('height_cm', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('vol_weight_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('physical_weight_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_packages_order_id'), 'order_packages', ['order_id'], unique=False)
    op.create_table('order_reviews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('review', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_reviews_order_id'), 'order_reviews', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_reviews_user_id'), 'order_reviews', ['user_id'], unique=False)
    op.create_table('order_warehouse_addresses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('warehouse_address_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_address_id'], ['warehouse_addresses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pickupstoconsignees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pincode', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('order_id', sa.String(length=36), nullable=True),
    sa.Column('pickup_addresses_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pickup_addresses_id'], ['pickup_addresses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pickupstoconsignees_id'), 'pickupstoconsignees', ['id'], unique=False)
    op.create_index(op.f('ix_pickupstoconsignees_user_id'), 'pickupstoconsignees', ['user_id'], unique=False)
    op.create_table('pod_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('receiver_name', sa.String(length=150), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('delivery_staff_id', sa.String(length=36), nullable=True),
    sa.Column('otp_verified', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('signature_url', sa.Text(), nullable=True),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['delivery_staff_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pod_records_order_id'), 'pod_records', ['order_id'], unique=True)
    op.create_table('remittance_orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('remittance_id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('cod_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['remittance_id'], ['remittances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_remittance_orders_order_id'), 'remittance_orders', ['order_id'], unique=True)
    op.create_index(op.f('ix_remittance_orders_remittance_id'), 'remittance_orders', ['remittance_id'], unique=False)
    op.create_table('wallet_transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('wallet_id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('opening_balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('closing_balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_transactions_order_id'), 'wallet_transactions', ['order_id'], unique=False)
    op.create_index(op.f('ix_wallet_transactions_wallet_id'), 'wallet_transactions', ['wallet_id'], unique=False)
    op.create_table('warehousetodelivery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pincode', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('order_id', sa.String(length=36), nullable=True),
    sa.Column('warehouse_addresses_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_addresses_id'], ['warehouse_addresses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehousetodelivery_id'), 'warehousetodelivery', ['id'], unique=False)
    op.create_index(op.f('ix_warehousetodelivery_user_id'), 'warehousetodelivery', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_warehousetodelivery_user_id'), table_name='warehousetodelivery')
    op.drop_index(op.f('ix_warehousetodelivery_id'), table_name='warehousetodelivery')
    op.drop_table('warehousetodelivery')
    op.drop_index(op.f('ix_wallet_transactions_wallet_id'), table_name='wallet_transactions')
    op.drop_index(op.f('ix_wallet_transactions_order_id'), table_name='wallet_transactions')
    op.drop_table('wallet_transactions')
    op.drop_index(op.f('ix_remittance_orders_remittance_id'), table_name='remittance_orders')
    op.drop_index(op.f('ix_remittance_orders_order_id'), table_name='remittance_orders')
    op.drop_table('remittance_orders')
    op.drop_index(op.f('ix_pod_records_order_id'), table_name='pod_records')
    op.drop_table('pod_records')
    op.drop_index(op.f('ix_pickupstoconsignees_user_id'), table_name='pickupstoconsignees')
    op.drop_index(op.f('ix_pickupstoconsignees_id'), table_name='pickupstoconsignees')
    op.drop_table('pickupstoconsignees')
    op.drop_table('order_warehouse_addresses')
    op.drop_index(op.f('ix_order_reviews_user_id'), table_name='order_reviews')
    op.drop_index(op.f('ix_order_reviews_order_id'), table_name='order_reviews')
    op.drop_table('order_reviews')
    op.drop_index(op.f('ix_order_packages_order_id'), table_name='order_packages')
    op.drop_table('order_packages')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_table('order_franchise_addresses')
    op.drop_index(op.f('ix_manifest_orders_order_id'), table_name='manifest_orders')
    op.drop_index(op.f('ix_manifest_orders_manifest_id'), table_name='manifest_orders')
    op.drop_table('manifest_orders')
    op.drop_index(op.f('ix_invoice_orders_order_id'), table_name='invoice_orders')
    op.drop_index(op.f('ix_invoice_orders_invoice_id'), table_name='invoice_orders')
    op.drop_table('invoice_orders')
    op.drop_index(op.f('ix_franchisetodelivery_user_id'), table_name='franchisetodelivery')
    op.drop_index(op.f('ix_franchisetodelivery_id'), table_name='franchisetodelivery')
    op.drop_table('franchisetodelivery')
    op.drop_index(op.f('ix_consigneestodelivery_user_id'), table_name='consigneestodelivery')
    op.drop_index(op.f('ix_consigneestodelivery_id'), table_name='consigneestodelivery')
    op.drop_table('consigneestodelivery')
    op.drop_index(op.f('ix_bag_orders_order_id'), table_name='bag_orders')
    op.drop_index(op.f('ix_bag_orders_bag_id'), table_name='bag_orders')
    op.drop_table('bag_orders')
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.drop_index(op.f('ix_orders_franchise_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_created_by'), table_name='orders')
    op.drop_index(op.f('ix_orders_bulk_order_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_bulk_orders_franchise_id'), table_name='bulk_orders')
    op.drop_index(op.f('ix_bulk_orders_created_by'), table_name='bulk_orders')
    op.drop_table('bulk_orders')
    op.drop_index(op.f('ix_warehouse_addresses_user_id'), table_name='warehouse_addresses')
    op.drop_index(op.f('ix_warehouse_addresses_pincode'), table_name='warehouse_addresses')
    op.drop_index(op.f('ix_warehouse_addresses_franchise_id'), table_name='warehouse_addresses')
    op.drop_table('warehouse_addresses')
    op.drop_index(op.f('ix_wallets_franchise_id'), table_name='wallets')
    op.drop_table('wallets')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_staff_attendance_user_id'), table_name='staff_attendance')
    op.drop_index(op.f('ix_staff_attendance_franchise_id'), table_name='staff_attendance')
    op.drop_index(op.f('ix_staff_attendance_attendance_date'), table_name='staff_attendance')
    op.drop_table('staff_attendance')
    op.drop_table('role_permissions')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_remittances_franchise_id'), table_name='remittances')
    op.drop_table('remittances')
    op.drop_index(op.f('ix_pickup_addresses_user_id'), table_name='pickup_addresses')
    op.drop_index(op.f('ix_pickup_addresses_pincode'), table_name='pickup_addresses')
    op.drop_index(op.f('ix_pickup_addresses_franchise_id'), table_name='pickup_addresses')
    op.drop_table('pickup_addresses')
    op.drop_index(op.f('ix_manifests_manifest_no'), table_name='manifests')
    op.drop_index(op.f('ix_manifests_manifest_date'), table_name='manifests')
    op.drop_index(op.f('ix_manifests_franchise_id'), table_name='manifests')
    op.drop_index(op.f('ix_manifests_created_by'), table_name='manifests')
    op.drop_table('manifests')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_franchise_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_expenses_franchise_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_created_by'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_consignees_user_id'), table_name='consignees')
    op.drop_index(op.f('ix_consignees_pincode'), table_name='consignees')
    op.drop_index(op.f('ix_consignees_franchise_id'), table_name='consignees')
    op.drop_table('consignees')
    op.drop_index(op.f('ix_cash_vouchers_voucher_no'), table_name='cash_vouchers')
    op.drop_index(op.f('ix_cash_vouchers_franchise_id'), table_name='cash_vouchers')
    op.drop_index(op.f('ix_cash_vouchers_created_by'), table_name='cash_vouchers')
    op.drop_table('cash_vouchers')
    op.drop_index(op.f('ix_bags_pincode'), table_name='bags')
    op.drop_index(op.f('ix_bags_created_by'), table_name='bags')
    op.drop_index(op.f('ix_bags_bag_number'), table_name='bags')
    op.drop_table('bags')
    op.drop_index(op.f('ix_activity_logs_user_id'), table_name='activity_logs')
    op.drop_table('activity_logs')
    op.drop_index(op.f('ix_users_franchise_id'), table_name='users')
    op.drop_index(op.f('ix_users_employee_code'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_rate_zones_zone_name'), table_name='rate_zones')
    op.drop_table('rate_zones')
    op.drop_index(op.f('ix_rate_cards_zone'), table_name='rate_cards')
    op.drop_index(op.f('ix_rate_cards_shipment_type'), table_name='rate_cards')
    op.drop_index(op.f('ix_rate_cards_customer_type'), table_name='rate_cards')
    op.drop_table('rate_cards')
    op.drop_index(op.f('ix_pricing_zones_zone_name'), table_name='pricing_zones')
    op.drop_index(op.f('ix_pricing_zones_pickup_region'), table_name='pricing_zones')
    op.drop_index(op.f('ix_pricing_zones_delivery_region'), table_name='pricing_zones')
    op.drop_table('pricing_zones')
    op.drop_index(op.f('ix_pricing_rules_shipment_type'), table_name='pricing_rules')
    op.drop_index(op.f('ix_pricing_rules_risk_type'), table_name='pricing_rules')
    op.drop_index(op.f('ix_pricing_rules_payment_mode'), table_name='pricing_rules')
    op.drop_index(op.f('ix_pricing_rules_calculator_type'), table_name='pricing_rules')
    op.drop_table('pricing_rules')
    op.drop_table('pincode_serviceability')
    op.drop_index(op.f('ix_permissions_module'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_action'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_table('gst_config')
    op.drop_table('fuel_config')
    op.drop_index(op.f('ix_franchises_franchise_code'), table_name='franchises')
    op.drop_table('franchises')
    op.drop_table('franchise_code_counter')
    # ### end Alembic commands ###
