"""add new changes

Revision ID: 2386a184b3da
Revises: a6c5054cfdb6
Create Date: 2026-06-02 16:42:12.840342

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '2386a184b3da'
down_revision: Union[str, None] = 'a6c5054cfdb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
