"""update auth user profile

Revision ID: 2c219f94d4d5
Revises: 6e4dab02a668
Create Date: 2026-06-23 16:06:29.805742

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = '2c219f94d4d5'
down_revision: Union[str, None] = '6e4dab02a668'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profiles')
    op.drop_column('auth_user_profiles', 'website')
    op.drop_column('auth_user_profiles', 'designation')
    op.drop_column('auth_user_profiles', 'company')
    op.drop_column('auth_user_profiles', 'profile_image_public_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_user_profiles', sa.Column('profile_image_public_id', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('auth_user_profiles', sa.Column('company', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('auth_user_profiles', sa.Column('designation', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('auth_user_profiles', sa.Column('website', mysql.VARCHAR(length=200), nullable=True))
    op.create_table('user_profiles',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('last_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('phone', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('alternate_phone', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('date_of_birth', mysql.DATETIME(), nullable=True),
    sa.Column('gender', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('address_line_1', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('address_line_2', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('city', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('state', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('pincode', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('country', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('profile_image_url', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('profile_image_public_id', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('bio', mysql.TEXT(), nullable=True),
    sa.Column('company', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('designation', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('website', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('facebook', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('twitter', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('instagram', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('linkedin', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('language', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('timezone', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('notification_enabled', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], name=op.f('user_profiles_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('user_id'), 'user_profiles', ['user_id'], unique=True)
    # ### end Alembic commands ###
