"""fix date wise status address api

Revision ID: 699a2eea68f3
Revises: 22f40f683295
Create Date: 2026-05-29 21:31:57.914476

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '699a2eea68f3'
down_revision: Union[str, None] = '22f40f683295'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
