"""create product table

Revision ID: 6e4dab02a668
Revises: 6c4135d06295
Create Date: 2026-06-23 11:34:34.502955

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = '6e4dab02a668'
down_revision: Union[str, None] = '6c4135d06295'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_franchise_applications_byuser_email'), table_name='franchise_applications_byuser')
    op.drop_index(op.f('ix_franchise_applications_byuser_pincode'), table_name='franchise_applications_byuser')
    op.drop_table('franchise_applications_byuser')
    op.alter_column('invoices', 'franchise_id',
               existing_type=mysql.VARCHAR(length=36),
               nullable=True)
    op.drop_constraint(op.f('reviews_ibfk_1'), 'reviews', type_='foreignkey')
    op.create_foreign_key(None, 'reviews', 'auth_users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_roles_franchise_id'), 'roles', ['franchise_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roles_franchise_id'), table_name='roles')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.create_foreign_key(op.f('reviews_ibfk_1'), 'reviews', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('invoices', 'franchise_id',
               existing_type=mysql.VARCHAR(length=36),
               nullable=False)
    op.create_table('franchise_applications_byuser',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=20), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('full_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('phone', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('date_of_birth', sa.DATE(), nullable=True),
    sa.Column('gender', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('current_address', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('permanent_address', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('proposed_location', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ownership_type', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('detailed_business_address', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('prior_experience', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('years_active', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('office_space_sqft', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('office_ownership', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('staff_count', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('internet_availability', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('computer_laptop', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('investment_capacity', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('source_of_funds', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('bank_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('account_number', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('existing_loans', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('existing_loan_details', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('preferred_service_area', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('nearby_landmark', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('pincode', mysql.VARCHAR(length=6), nullable=False),
    sa.Column('aadhar_file_path', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('pan_file_path', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('photo_file_path', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('business_registration_file_path', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('bank_statement_file_path', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('doc_id_proof', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('doc_address_proof', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('doc_photographs', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('doc_business_registration', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('doc_bank_statement', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('agree_to_terms', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('submission_place', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('submission_date', sa.DATE(), nullable=True),
    sa.Column('admin_remarks', mysql.TEXT(), nullable=True),
    sa.Column('approved_by', mysql.VARCHAR(length=36), nullable=True),
    sa.Column('approved_at', mysql.DATETIME(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('franchise_applications_byuser_ibfk_2'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_franchise_applications_byuser_pincode'), 'franchise_applications_byuser', ['pincode'], unique=False)
    op.create_index(op.f('ix_franchise_applications_byuser_email'), 'franchise_applications_byuser', ['email'], unique=False)
    # ### end Alembic commands ###
