"""add new changes

Revision ID: a6c5054cfdb6
Revises: afb32e133730
Create Date: 2026-06-02 15:23:23.761511

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'a6c5054cfdb6'
down_revision: Union[str, None] = 'afb32e133730'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
