"""update models

Revision ID: afb32e133730
Revises: f27cd92d7afa
Create Date: 2026-06-01 12:48:14.756084

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'afb32e133730'
down_revision: Union[str, None] = 'f27cd92d7afa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
