"""add new fields to model

Revision ID: f27cd92d7afa
Revises: 699a2eea68f3
Create Date: 2026-05-30 10:24:58.722776

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'f27cd92d7afa'
down_revision: Union[str, None] = '699a2eea68f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bags', sa.Column('previous_status', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bags', 'previous_status')
    # ### end Alembic commands ###
