"""initial migration

Revision ID: f943fcc61fd0
Revises: 
Create Date: 2026-06-26 14:41:37.642967

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'f943fcc61fd0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
